#!/usr/bin/env bash
#
# build.sh — regenerate install.sh by stitching:
#   1. wrapper shell logic (this file's heredocs)
#   2. scripts/rotator.py (verbatim, embedded via heredoc)
#   3. templates/com.cswap-rotator.plist.tmpl (verbatim, embedded via heredoc)
#
# Run after editing rotator.py / plist tmpl / wrapper logic.
#
set -euo pipefail
cd "$(dirname "$0")"

OUT=install.sh
ROTATOR=scripts/rotator.py
PLIST=templates/com.cswap-rotator.plist.tmpl

# Sanity: heredoc terminators must not appear inside the embedded files.
for f in "$ROTATOR" "$PLIST"; do
    if grep -qE "^(ROTATOR_PY_END|PLIST_TMPL_END)$" "$f"; then
        echo "ERROR: heredoc delimiter collision in $f" >&2; exit 1
    fi
done

# ============================================================================
# Part 1: header + preflight + dependency auto-install
# ============================================================================
cat > "$OUT" <<'INSTALLER_HEAD_END'
#!/usr/bin/env bash
# ============================================================================
# AUTO-GENERATED BY build.sh — DO NOT HAND-EDIT.
# Source files: scripts/rotator.py, templates/*, build.sh
# Re-run `bash build.sh` after editing any source.
# ============================================================================
#
# cswap-rotator one-line installer (macOS).
# Auto-installs uv and cswap if missing.
#
# Distribution (private repo, internal use):
#   git clone git@github.com:Ailoha-ai/cswap-rotator.git
#   cd cswap-rotator && bash install.sh
#
# Usage:
#   bash install.sh                                # default install
#   bash install.sh --threshold 95 --margin 25     # with overrides
#   bash install.sh --uninstall                    # remove (preserve config + log)
#   bash install.sh --purge                        # remove everything
#
# Defaults: threshold=90  margin=30  grace=15  dry_run=false  adaptive_polling=true
#
set -euo pipefail

THRESHOLD=90
MARGIN=30
GRACE=15
DRY_RUN=false
ACTION=install

INSTALL_ROOT="${HOME}/.cswap-rotator"
CONFIG_DIR="${HOME}/.config/cswap-rotator"
LOG_PATH="${HOME}/Library/Logs/cswap-rotator.log"
PLIST_PATH="${HOME}/Library/LaunchAgents/com.cswap-rotator.plist"
LABEL="com.cswap-rotator"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --threshold) THRESHOLD="$2"; shift 2 ;;
        --margin)    MARGIN="$2";    shift 2 ;;
        --grace)     GRACE="$2";     shift 2 ;;
        --dry-run)   DRY_RUN="$2";   shift 2 ;;
        --uninstall) ACTION=uninstall; shift ;;
        --purge)     ACTION=purge;    shift ;;
        -h|--help)
            cat <<HELP
cswap-rotator installer

Flags:
  --threshold N        active 5h% triggering evaluation (default 90)
  --margin N           pp gap below active for "comfortable" switch (default 30)
  --grace N            skip switch if active resets within N min (default 15)
  --dry-run BOOL       true=log only, false=really switch (default false — live)
  --uninstall          remove plist + scripts (preserve config + log)
  --purge              also wipe ~/.config/cswap-rotator and the log file

Auto-installs (if missing): uv, cswap (claude-swap).
Account login is interactive — must be done by user separately.
HELP
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

# ----------------------------------------------------------------------------
# Uninstall paths
# ----------------------------------------------------------------------------
if [[ "$ACTION" == "uninstall" || "$ACTION" == "purge" ]]; then
    echo "=== cswap-rotator uninstall ==="
    if [[ -f "$PLIST_PATH" ]]; then
        launchctl unload "$PLIST_PATH" 2>/dev/null || true
        rm "$PLIST_PATH"
        echo "✓ LaunchAgent unloaded"
    fi
    [[ -d "$INSTALL_ROOT" ]] && { rm -rf "$INSTALL_ROOT"; echo "✓ removed $INSTALL_ROOT"; }
    if [[ "$ACTION" == "purge" ]]; then
        [[ -d "$CONFIG_DIR" ]] && { rm -rf "$CONFIG_DIR"; echo "✓ removed $CONFIG_DIR"; }
        [[ -f "$LOG_PATH"   ]] && { rm    "$LOG_PATH";   echo "✓ removed $LOG_PATH"; }
        echo "=== fully purged ==="
    else
        echo "Preserved (use --purge to also remove):"
        [[ -d "$CONFIG_DIR" ]] && echo "  - $CONFIG_DIR"
        [[ -f "$LOG_PATH"   ]] && echo "  - $LOG_PATH"
    fi
    echo "Note: cswap and uv are left installed (this script doesn't manage them)."
    exit 0
fi

# ----------------------------------------------------------------------------
# Install: preflight + dependency bootstrap
# ----------------------------------------------------------------------------
echo "=== cswap-rotator install ==="
[[ "$(uname)" == "Darwin" ]] || { echo "ERROR: macOS only"; exit 1; }

# Ensure ~/.local/bin is searchable for this run (uv tools land here)
export PATH="${HOME}/.local/bin:${PATH}"

# --- uv -------------------------------------------------------------------
if ! command -v uv >/dev/null 2>&1; then
    echo "→ uv not found, installing from https://astral.sh/uv/install.sh ..."
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null
    export PATH="${HOME}/.local/bin:${PATH}"
fi
command -v uv >/dev/null 2>&1 || { echo "ERROR: uv install failed"; exit 1; }
echo "✓ uv: $(command -v uv)"

# --- cswap ----------------------------------------------------------------
if ! command -v cswap >/dev/null 2>&1; then
    echo "→ cswap not found, installing via 'uv tool install claude-swap' ..."
    uv tool install claude-swap >/dev/null
    export PATH="${HOME}/.local/bin:${PATH}"
fi
command -v cswap >/dev/null 2>&1 || { echo "ERROR: cswap install failed"; exit 1; }
echo "✓ cswap: $(command -v cswap)"

# --- python with claude_swap module ----------------------------------------
CSWAP_PYTHON=""
for c in "${HOME}/.local/share/uv/tools/claude-swap/bin/python" "$(command -v python3 || true)"; do
    if [[ -x "$c" ]] && "$c" -c "import claude_swap" 2>/dev/null; then
        CSWAP_PYTHON="$c"; break
    fi
done
[[ -n "$CSWAP_PYTHON" ]] || { echo "ERROR: no Python with claude_swap module"; exit 1; }
echo "✓ python: $CSWAP_PYTHON"

# --- accounts (info only — adding accounts is interactive, can't automate) -
ACCT_COUNT=$(cswap --status 2>/dev/null | grep -oE 'Total managed accounts: [0-9]+' | grep -oE '[0-9]+' || echo "0")
if [[ "$ACCT_COUNT" -lt 2 ]]; then
    cat <<NOTE
⚠ Only $ACCT_COUNT cswap account(s) detected.
  rotator needs ≥2 to do anything; until then it just skips silently.
  Add accounts (in a GUI Terminal — needs browser login):
    1. claude            # log in to your first account
    2. cswap --add-account
    3. claude /logout    # then log in to your next account
    4. cswap --add-account
NOTE
else
    echo "✓ accounts: $ACCT_COUNT"
fi

mkdir -p "$INSTALL_ROOT/scripts" "$INSTALL_ROOT/templates" \
         "$CONFIG_DIR" "$(dirname "$LOG_PATH")"

# ----------------------------------------------------------------------------
# Embedded files (heredocs follow)
# ----------------------------------------------------------------------------
cat > "$INSTALL_ROOT/scripts/rotator.py" <<'ROTATOR_PY_END'
INSTALLER_HEAD_END

# ============================================================================
# Part 2: append rotator.py verbatim
# ============================================================================
cat "$ROTATOR" >> "$OUT"

# ============================================================================
# Part 3: close rotator heredoc; open plist heredoc
# ============================================================================
cat >> "$OUT" <<'AFTER_ROTATOR'
ROTATOR_PY_END

cat > "$INSTALL_ROOT/templates/com.cswap-rotator.plist.tmpl" <<'PLIST_TMPL_END'
AFTER_ROTATOR

# ============================================================================
# Part 4: append plist tmpl verbatim
# ============================================================================
cat "$PLIST" >> "$OUT"

# ============================================================================
# Part 5: closer + config write + plist render + load + done banner
# ============================================================================
cat >> "$OUT" <<'INSTALLER_TAIL_END'
PLIST_TMPL_END

# ----------------------------------------------------------------------------
# Config — preserve existing
# ----------------------------------------------------------------------------
if [[ -f "$CONFIG_DIR/config.json" ]]; then
    echo "✓ existing config preserved at $CONFIG_DIR/config.json"
else
    cat > "$CONFIG_DIR/config.json" <<EOF
{
  "rotate_threshold_pct": ${THRESHOLD},
  "safety_margin_pct": ${MARGIN},
  "reset_grace_min": ${GRACE},
  "dry_run": ${DRY_RUN},
  "adaptive_polling": true
}
EOF
    echo "✓ config written: $CONFIG_DIR/config.json (dry_run=$DRY_RUN)"
fi

# ----------------------------------------------------------------------------
# Render plist + load
# ----------------------------------------------------------------------------
sed -e "s|__PYTHON__|${CSWAP_PYTHON}|" \
    -e "s|__SCRIPT__|${INSTALL_ROOT}/scripts/rotator.py|" \
    -e "s|__LOG__|${LOG_PATH}|" \
    "$INSTALL_ROOT/templates/com.cswap-rotator.plist.tmpl" > "$PLIST_PATH"
echo "✓ plist rendered: $PLIST_PATH"

launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"
echo "✓ LaunchAgent loaded ($LABEL)"

cat <<DONE

=== installed ===
  scripts: $INSTALL_ROOT
  config:  $CONFIG_DIR/config.json
  log:     $LOG_PATH
  plist:   $PLIST_PATH

  threshold ${THRESHOLD}% / margin ${MARGIN}pp / grace ${GRACE}min / dry_run ${DRY_RUN}

  - first run fires within seconds (RunAtLoad), then every 10 min
  - tail logs:  tail -f $LOG_PATH
  - pause:      launchctl unload $PLIST_PATH
  - resume:     launchctl load   $PLIST_PATH
  - uninstall:  bash install.sh --uninstall
DONE
INSTALLER_TAIL_END

chmod +x "$OUT"
echo "=== built ==="
echo "  size:  $(wc -l < $OUT) lines / $(wc -c < $OUT) bytes"
echo "  path:  $(pwd)/$OUT"
echo "  sha:   $(shasum -a 256 $OUT | awk '{print $1}')"
